### ISSUE TITLE
PHP 8.4 support

### ISSUE THREAD

**Issue by abramchikd** [phpmd/phpmd#1219]
Hello! I'm enjoying this library very much, but it is not compatible with the latest PHP version 8.4. To be exact it fails when parsing files with [new without parentheses](https://wiki.php.net/rfc/new_without_parentheses). Are there any plans to add PHP 8.4 support

**Comment by AJenbo** [comment]
Yes, did you test the 3.x branch? What error does it throw?

**Comment by abramchikd** [comment]
Sorry for a late response.

```bash
ERROR while parsing 
--------------------
Unexpected token: ->, line: 34, col: 39, file: /app/src/Vacancy/Scheduler/RejectApplications.php.
#0 /app/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(8741): PDepend\Source\Parser\UnexpectedTokenException->__construct(Object(PDepend\Source\Tokenizer\Token), '/app/src/Vacanc...')
```

For the following code:
```
$timeoutDate = new DatePoint()->add($dateInterval);
```

**Comment by JyskFynskeMedierJoej** [comment]
+1 For PHP 8.4 support - we use and like PHPMD very much as well. 

We are in the process of updating around 120 packages that use PHPMD. We get a lot of deprecated warnings of this type: 
**_Implicitly marking parameter $type as nullable is deprecated, the explicit nullable type must be used instead_**

Hope you can find the time to fix the issue in the near future :)

**Comment by AJenbo** [comment]
@JyskFynskeMedierJoej skifte til 3.x så vil den køre fint på 8.4, dog understøtter denne ikke kode der bruger nye ting fra 8.4 endnu.

**Comment by glo71317** [comment]
Hi @AJenbo I tested 3.x-dev, i tested it looks fine to me, Could we be planning to release the major version sooner, considering that PHP 8.4 has been out for almost two months now?

**Comment by AJenbo** [comment]
The other maintainers return next week and then we will look into the two missing features and an eventual release

**Comment by Axent96** [comment]
@AJenbo do you have any info for plan of next release?

**Comment by AJenbo** [comment]
We just finished the update to PHPStan 2.1 on PDepend today which was the first step in resuming development.

**Comment by Axent96** [comment]
@AJenbo any plan for release date? the change is already present, or?

**Comment by AJenbo** [comment]
Sorry I'm not the person in charge of releases

**Comment by byWulf** [comment]
Who is in charge of releases? @AJenbo

**Comment by AJenbo** [comment]
You can see it for all project on this page: https://github.com/phpmd/phpmd/releases

**Comment by kylekatarnls** [comment]
Hello, I'm considering releasing an alpha version, but would challenge how useful it is. It will be an alpha since 3.0 version is not finished, until the stable versions, breaking changes will happen.

Currently it's already possible to install the version 3 using `composer require "pdepend/pdepend:3.x-dev" "phpmd/phpmd:3.x-dev" --dev`

While composer way is recommended, it's also possible to get the phar from:
https://github.com/phpmd/phpmd/commits/3.x/

![Image](https://github.com/user-attachments/assets/1221c49b-7a67-42e4-865c-30cca6f3506d)

Then click Summary > artifact:

![Image](https://github.com/user-attachments/assets/f2295d02-5801-4c71-9017-c879708f7054)

So from my understanding you can already get the in-progress PHPMD 3.0 from composer or its phar version, so there should be no blocker use it anywhere and get PHP 8.4 partial support, then an alpha release of it would not allow you to do anything more as far as I can tell.

Please let me know if there are other needs not covered by the installation methods above.

**Comment by evs-xsarus** [comment]
I've added these to my composer.json:

```json
        "phpmd/phpmd": "3.x-dev#3a8f6ed5293a244cdf4ec3a4f1ebc32db1dadf27",
        "pdepend/pdepend": "3.x-dev#5fddc0476146acf1455bd4cccf83f20439a0335b",
```

But now, I got lot's of false positives on UnusedPrivateField and UnusedPrivateMethod .

**Comment by judimator** [comment]
HI there!

@AJenbo I faced with same issue `Unexpected token: ->, line: 27, col: 62, file...` for ` $expirationDate = new \DateTimeImmutable('+1 minute')->getTimestamp();`.

I tried what @evs-xsarus suggested but is did not help me.


I performed:

- `composer require "pdepend/pdepend:3.x-dev" "phpmd/phpmd:3.x-dev" --dev`
- `./vendor/bin/phpmd src text phpmd.xml`

**pdepend/pdepend:3.x-dev** (04632709b73ef136bcc5b5b32708bc130df0ca2e)
**phpmd/phpmd** (3a8f6ed5293a244cdf4ec3a4f1ebc32db1dadf27)


Any ideas?

Thank you!

**Comment by AJenbo** [comment]
use 8.3 syntax: `$expirationDate = (new \DateTimeImmutable('+1 minute'))->getTimestamp();.`

**Comment by evs-xsarus** [comment]
I'm now using

```json
    "phpmd/phpmd": "^2.15",
```

with these patches:

```diff
--- a/vendor/phpmd/phpmd/src/main/php/PHPMD/Report.php
+++ b/vendor/phpmd/phpmd/src/main/php/PHPMD/Report.php
@@ -58,7 +58,7 @@
     /** @var BaselineValidator|null */
     private $baselineValidator;

-    public function __construct(BaselineValidator $baselineValidator = null)
+    public function __construct(?BaselineValidator $baselineValidator = null)
     {
         $this->baselineValidator = $baselineValidator;
     }

--- a/vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/UnusedPrivateField.php
+++ b/vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/UnusedPrivateField.php
@@ -147,7 +147,7 @@
      * @return boolean
      * @since 0.2.6
      */
-    protected function isValidPropertyNode(ASTNode $node = null)
+    protected function isValidPropertyNode(?ASTNode $node = null)
     {
         if ($node === null) {
             return false;

```

this makes phpmd installable and runable. It just doesn't check for any specific PHP 8.4 syntaxes.

**Comment by AJenbo** [comment]
@evs-xsarus PHPMD 3.x-dev has these changes already you can simply install it instead of 2.x

**Comment by AJenbo** [comment]
I'm usually not the one who add language support

**Comment by josep11** [comment]
+1 on this issue

**Comment by talha-core** [comment]
following

**Comment by Floberrot** [comment]
I would like to bypass the error of this : [parenthesis](https://wiki.php.net/rfc/new_without_parentheses). I am not in dev for now, and I can't right now. I just want to bypass the errors until i can upgrade

**Comment by AJenbo** [comment]
The 8.4 syntax is not supported, there is no way to by pass that other then using 8.3 syntax.

**Comment by AJenbo** [comment]
[new without parentheses](https://wiki.php.net/rfc/new_without_parentheses) is now supported in 3.x

**Comment by AJenbo** [comment]
please see https://github.com/phpmd/phpmd/issues/1237 regarding support for Property hooks

**Comment by AJenbo** [comment]
> But now, I got lot's of false positives on UnusedPrivateField and UnusedPrivateMethod .
> 
> Edit: found a ticket [#1236](https://github.com/phpmd/phpmd/pull/1236) 1216

This has also been addressed in 3.x-dev

**Comment by AJenbo** [comment]
All 8.4 features should now be supported in the latest 3.x-dev and 8.5 support is being reviewed and should land very shortly.

**Comment by AJenbo** [comment]
8.5 syntax is now supported

**Comment by arg187** [comment]
<img width="889" height="636" alt="Image" src="https://github.com/user-attachments/assets/1524ac8c-4e70-466c-89a5-77a96c2d226d" />

Packagist is still showing 2.15 as the latest version ?

**Comment by kylekatarnls** [comment]
`3.x-dev` means it's a dev version,, you need to use:

```
composer require "phpmd/phpmd:^3@dev" "pdepend/pdepend:^3@dev"
```

**Comment by AJenbo** [comment]
We still have a few changes and features we would like to land before releasing 3.0 as a stable version. I'm going to to be working on that though December so hopefully we can have a new release before to long.

<img width="1147" height="219" alt="Image" src="https://github.com/user-attachments/assets/769b6c76-d6f4-4b33-aa40-59b4f47be598" />

**Comment by rafaelpouzada** [comment]
Any update on the release of version 3?

**Comment by AJenbo** [comment]
It's the next thing I want to get done, this is my current list of things competing for time:

- Work
- PHPMD 3.0
- ~~[PHPantom](https://github.com/AJenbo/phpantom_lsp) 0.8.0~~
- ~~Prepare my presentation on PHPantom (deadline Wednesday)~~
- ~~https://github.com/SpartnerNL/Laravel-Excel/issues/4345~~
- ~~https://github.com/diasurgical/DevilutionX/issues/8541~~
- ~~https://github.com/isledecomp/isle-portable/pull/800~~
- https://github.com/diasurgical/DevilutionX/pull/8586
- https://github.com/bladestan/bladestan/pull/183
- Maintain fragments of a social life
- Clean my apartment

So you should start seeing progress soon.

**Comment by AJenbo** [comment]
I have decided to not delay my LSP for the PHPMD 3.0 release, but hopefully you can tell that it's not because I'm not working on it. We have made a lot of progress this week with 18 PR merged and several issues closed, and 5 new PRs ready for review.

I'm going to be away for a few days on and off but on Wednesday I'll be back full speed again and should be able to finish what's left that week or close to it since at this point there's less then 10 issues left to deal with.

Thank you to everyone that's helping with testing.

**Comment by AJenbo** [comment]
Had at take a break while working on a few other things, but back at it. I think today we hit what can be called a release candidate status.

There are still 5 PR planned for the code (2 already up for review) and one for the documentation. I really do think we can finish it before next week, the only thing in question then is the actual release process.

P.s. @lussoluca has been helping out which fixing some issues which is always a big boost to moral.
