### ISSUE TITLE
Variadic functions.

### ISSUE THREAD

**Issue by bweston92** [phpmd/phpmd#279]
Issue with variadic functions arguments. (PHP 5.6.7-1)

```
{file} - Unexpected token: ..., line: 182, col: 49, file: {file}.
```

**Comment by megawebmaster** [comment]
Any news on solution to this problem?

**Comment by manuelpichler** [comment]
I am currently solving this issue in PDepend.

**Comment by ravage84** [comment]
@manuelpichler do you have any issue number, so we can cross link this?

**Comment by manuelpichler** [comment]
Just created it pdepend/pdepend#202

**Comment by JeroenDeDauw** [comment]
Is there a way to suppress this error, for instance by disabling some inspection?

**Comment by ravage84** [comment]
I guess you would need to exclude the file for the moment, @JeroenDeDauw

**Comment by JeroenDeDauw** [comment]
Thanks for the quick reply.

I know that can be done with ` --exclude`. Is it possible to list the files to exclude in the XML config?

**Comment by ravage84** [comment]
@JeroenDeDauw thanks for asking. Funny enough, it actually seems there is, though it's kind of undocumented.

https://github.com/phpmd/phpmd/pull/100
https://github.com/phpmd/phpmd/blob/7c293efb29c54f10398e4c9667043c0c3342e1a7/CHANGELOG#L238
https://github.com/phpmd/phpmd/blob/7c293efb29c54f10398e4c9667043c0c3342e1a7/src/test/resources/files/rulesets/exclude-pattern.xml#L21
http://pmd.sourceforge.net/pmd-5.0.4/howtomakearuleset.html#Excluding_files_from_a_ruleset

Please give it a try.
I'll added issue https://github.com/phpmd/phpmd/issues/373 to document it.

**Comment by ravage84** [comment]
I think this should be resolved by now, as https://github.com/pdepend/pdepend/issues/202 was merged.
But I guess we could add a regression test in phpmd for the variadic function.

**Comment by JeroenDeDauw** [comment]
https://github.com/pdepend/pdepend/issues/202 is a ticket that was closed while none of the linked PRs where merged. Did you mean to link something else?

**Comment by ravage84** [comment]
@JeroenDeDauw pdepend/pdepend#202 was closed through https://github.com/pdepend/pdepend/commit/dff2547f0073e04aa6d7d0895ba2cc94deda20ac

**Comment by bartosz-maciaszek** [comment]
I'm still having this issue on PHPMD 2.4.3 (PHP 7.0.x). Any news on it?

**Comment by AntonShevel** [comment]
I'm having the same issue with PHP 5.6.18 and PHPMD 2.4.3
`Unexpected token: ..., line: 73, col: 46, file:`

**Comment by stephenharris** [comment]
I'm having this issue too (PHPMD 2.4.3, PDepend 2.2.4). It seems PDepend fixed this for the use of the `...` token in declarations, but not in function calls. See: https://github.com/pdepend/pdepend/issues/204

There's no patch yet, but the ticket is marked for the 2.3.0 release.

**Comment by bartosz-maciaszek** [comment]
A similar error occurs when phpmd hits `??`.
`Unexpected token: ??, line: x, col: y, file: z`

**Comment by bweston92** [comment]
Any updates?

**Comment by manuelpichler** [comment]
This is implemented in the latest pdepend versiuon and will be available with hte next release of phpmd

**Comment by bweston92** [comment]
Thanks, will close.

**Comment by pdenooijer** [comment]
Updating pdepend/pdepend will fix the problem.

**Comment by widoz** [comment]
I have the same problem, `pdepend/pdepend` is `2.5.2`, ` - Unexpected token: ..., line: 86, col: 44, ` I have a variadic method `public function __invoke(...$parameters)`

**Comment by tvbeek** [comment]
@widoz can you create a new issue (referencing to this one) with your code example? And please use the bug template so we get more information to find out what the problem is.
